import type { Metadata } from "next";
import "./globals.css";
import SidebarMenu from "@/components/SidebarMenu/SidebarMenu";

export const metadata: Metadata = {
    title: "CRM portfolio",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body>
            <div className="flex h-screen">
                <aside className="w-70 bg-amber-600">
                    <SidebarMenu />
                </aside>

                <main className="flex-1 p-6 bg-white rounded-l-2xl overflow-hidden">
                    {children}
                </main>
            </div>
        </body>
    </html>
  );
}
